# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x02pb\"\x1f\n\x0cHelloRequest\x12\x0f\n\x07Message\x18\x01 \x01(\t\"!\n\rHelloResponse\x12\x10\n\x08MessageR\x18\x01 \x01(\t27\n\x05Hello\x12.\n\x05Hello\x12\x10.pb.HelloRequest\x1a\x11.pb.HelloResponse\"\x00\x42!Z\x1fgithub.com/Zavr22/py-grpc-go/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037github.com/Zavr22/py-grpc-go/pb'
  _globals['_HELLOREQUEST']._serialized_start=19
  _globals['_HELLOREQUEST']._serialized_end=50
  _globals['_HELLORESPONSE']._serialized_start=52
  _globals['_HELLORESPONSE']._serialized_end=85
  _globals['_HELLO']._serialized_start=87
  _globals['_HELLO']._serialized_end=142
# @@protoc_insertion_point(module_scope)
